### ISSUE TITLE
Support transformers > 2.1.1 on Windows

### ISSUE THREAD

**Issue by dambuck** [conda-forge/transformers-feedstock#16]
Issue: conda installl transformers only up to 2.1.1

<br/>
Environment (<code>conda list</code>): 
<details>

```
$ conda list
win 10
Python 3.7.9, tf 2.1.0
```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):

When running conda install -c conda-forge transformers=version in a clean environment
I can only install 2.1.1, all other version which show up after a conda search, eg. 3.0.2 throw 

<details>

```
$ conda info
'<Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.- 
failed
UnsatisfiableError: The following specifications were found to be incompatible with each other:
Output in format: Requested package -> Available versions >'
```
</details>

Thank you very much

**Comment by setu4993** [comment]
@dambuck : This is because after 2.1.1 `sentencepiece` became a required requirement for transformers (see #3). The [sentencepiece-feedstock](https://github.com/conda-forge/sentencepiece-feedstock) on conda-forge is currently built and distributed only for Linux, so that's the only platform for which the latest versions of transformers can be supported.

**Comment by oblute** [comment]
Transformers now has windows support, now that sentencepiece got win functionality in https://github.com/conda-forge/sentencepiece-feedstock/pull/9 - closing this.
